const P=__PAYLOAD__, mapa=__MAPA__, camada=__CAMADA__;
const $=id=>document.getElementById(id), fmt=v=>v==null?'Sem dado':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:1});
const cores=['#edf8b1','#addd8e','#78c679','#31a354','#006837'];
let ano=String(Math.max(...P.info.anos)), metrica='214', selecionado=null, opacidade=.65;
for(let a=2020;a<=2026;a++){const o=new Option(a+(P.info.anos.includes(a)?'':' · sem dados no projeto'),a);o.disabled=!P.info.anos.includes(a);$('ano').add(o)}$('ano').value=ano;
Object.entries(P.metricas).forEach(([k,v])=>$('metrica').add(new Option(v[0]+' ('+v[1]+')',k)));
$('metrica').value=metrica;
Object.entries(P.nomes).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')).forEach(([k,v])=>$('municipios').appendChild(new Option(v,v)));
const escalas={};for(const k of Object.keys(P.metricas)){const vs=Object.values(P.dados).flatMap(a=>Object.values(a).map(v=>v[k])).filter(v=>v!=null&&v>0).sort((a,b)=>a-b);escalas[k]=[.2,.4,.6,.8].map(q=>vs[Math.min(vs.length-1,Math.floor(vs.length*q))]||0)}
function cor(v){if(v==null)return '#bcbcbc';if(v===0)return '#fff';let i=escalas[metrica].findIndex(b=>v<=b);return cores[i<0?4:i]}
function escapar(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const layers={};camada.eachLayer(l=>{const c=l.feature.properties.codigo;layers[c]=l;l.on('click',()=>abrir(c));l.on('mouseover',()=>l.setStyle({weight:2,color:'#183d2b'}));l.on('mouseout',()=>l.setStyle({weight:.8,color:'#617765'}))});
function abrir(c){const l=layers[c];if(!l)return;selecionado=c;mostrarSecao('historico');renderSerie();l.bindPopup('<b>'+escapar(P.nomes[c]||l.feature.properties.nome)+'</b><p>'+escapar(P.metricas[metrica][0])+': '+fmt(P.dados[ano]?.[c]?.[metrica])+' '+escapar(P.metricas[metrica][1])+' · '+ano+'</p><small>Histórico disponível no painel.</small>',{maxWidth:280}).openPopup()}
function atualizar(){ano=$('ano').value;metrica=$('metrica').value;mapa.closePopup();const d=P.dados[ano]||{},[titulo,unidade]=P.metricas[metrica];camada.eachLayer(l=>{let c=l.feature.properties.codigo,v=d[c]?.[metrica];l.setStyle({fillColor:cor(v),fillOpacity:opacidade,color:'#617765',weight:.8});l.unbindTooltip();l.bindTooltip(escapar(P.nomes[c]||l.feature.properties.nome)+': '+fmt(v)+' '+unidade)});
$('escopoTotal').textContent=metrica==='112'?'Rendimento médio estadual · IBGE/PAM':'Total estadual · IBGE/PAM';$('numero').textContent=fmt(P.estado[ano]?.['35']?.[metrica]);$('unidade').textContent=titulo+' · '+unidade;$('cobertura').textContent=Object.values(d).filter(v=>v[metrica]!=null).length+' municípios com valor numérico / 645 municípios no mapa.';
const bs=escalas[metrica];$('legenda').innerHTML='<b>'+titulo+' · '+unidade+'</b>'+cores.map((c,i)=>`<div class="legenda"><i class="chip" style="background:${c}"></i>${i===0?'Maior que 0 até '+fmt(bs[0]):i===4?'Acima de '+fmt(bs[3]):'Acima de '+fmt(bs[i-1])+' até '+fmt(bs[i])}</div>`).join('')+'<div class="legenda"><i class="chip" style="background:white"></i>Zero <i class="chip" style="background:#bcbcbc"></i>Sem dado</div>';
$('ranking').replaceChildren();const ranking=Object.entries(d).filter(([c,v])=>v[metrica]!=null&&v[metrica]>0).sort((a,b)=>b[1][metrica]-a[1][metrica]).slice(0,10);$('rankingNota').textContent=ano+' · '+unidade;ranking.forEach(([c,v],i)=>{const li=document.createElement('li'),b=document.createElement('button');b.innerHTML=`<span>${i+1}. ${escapar(P.nomes[c])}</span><strong>${fmt(v[metrica])}</strong>`;b.style.setProperty('--barra',(v[metrica]/ranking[0][1][metrica]*100).toFixed(1)+'%');b.onclick=()=>{mapa.fitBounds(layers[c].getBounds());abrir(c)};li.appendChild(b);$('ranking').appendChild(li)});renderSerie();renderVariacao();}
$('ano').onchange=atualizar;$('metrica').onchange=atualizar;
function localizar(){let termo=$('busca').value.trim().toLocaleLowerCase('pt-BR');let c=Object.keys(P.nomes).find(c=>P.nomes[c].toLocaleLowerCase('pt-BR')===termo);$('buscaStatus').textContent=c?'':'Selecione um município da lista.';if(c&&layers[c]){mapa.fitBounds(layers[c].getBounds());abrir(c)}}$('localizar').onclick=localizar;$('busca').onkeydown=e=>{if(e.key==='Enter')localizar()};
$('baixar').onclick=e=>{e.preventDefault();const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';let rows=[['ano','codigo_ibge','municipio',...Object.values(P.metricas).map(v=>v[0]+' ('+v[1]+')')],...Object.entries(P.dados[ano]).map(([c,v])=>[ano,c,P.nomes[c],...Object.keys(P.metricas).map(k=>v[k])])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='limao_sp_'+ano+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

function mostrarSecao(id){document.querySelectorAll('#painel .secao').forEach(s=>s.hidden=s.id!==id);document.querySelectorAll('[data-secao]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.secao===id)));document.querySelector('#painel .conteudo').scrollTop=0}
function renderVariacao(){const a=String(Number(ano)-1),v=P.estado[ano]?.['35']?.[metrica],antes=P.estado[a]?.['35']?.[metrica];$('variacao').textContent=v==null||antes==null?'Comparação anual indisponível.':antes===0?'Ano anterior: zero; variação percentual não calculável.':((v-antes)/antes>=0?'+':'')+fmt((v-antes)/antes*100)+'% em relação a '+a;}
function renderSerie(){
const codigo=selecionado||'35',base=selecionado?P.dados:P.estado,rotulo=selecionado?P.nomes[codigo]:'São Paulo';
$('serieTitulo').textContent=rotulo;$('serieIndicador').textContent=P.metricas[metrica].join(' · ');$('serieEstado').hidden=!selecionado;
const rows=P.info.anos.slice().sort((a,b)=>a-b).map(a=>({ano:String(a),valor:base[String(a)]?.[codigo]?.[metrica]??null}));
const max=Math.max(0,...rows.map(r=>r.valor??0)),width=320,height=210,left=16,right=16,top=32,bottom=42,plot=height-top-bottom,step=(width-left-right)/Math.max(1,rows.length);
let bars=rows.map((r,i)=>{const x=left+i*step+step*.18,w=step*.64,h=max>0&&r.valor!=null?r.valor/max*plot:0;
return '<g><title>'+r.ano+': '+fmt(r.valor)+' '+escapar(P.metricas[metrica][1])+'</title>'+(r.valor==null?'<text x="'+(x+w/2)+'" y="'+(height-bottom-8)+'" text-anchor="middle" font-size="10" fill="#66786d">s/d</text>':'<rect x="'+x+'" y="'+(height-bottom-h)+'" width="'+w+'" height="'+h+'" rx="3" fill="'+(r.ano===ano?'#477b34':'#abc18b')+'"/>')+'<text x="'+(x+w/2)+'" y="'+(height-bottom+20)+'" text-anchor="middle" font-size="11" fill="#304c3c">'+r.ano+'</text></g>'}).join('');
$('grafico').innerHTML='<svg viewBox="0 0 320 210" role="img" aria-label="Histórico de '+escapar(P.metricas[metrica][0])+' em '+escapar(rotulo)+'. Valores exatos na tabela abaixo."><text x="16" y="18" font-size="10" fill="#53685e">Máximo: '+fmt(max)+' '+escapar(P.metricas[metrica][1])+'</text><path d="M16 168 H304" stroke="#bac9bd" fill="none"/>'+bars+'</svg>';
$('serieTabela').innerHTML='<table class="serie"><caption>Valores anuais · '+escapar(P.metricas[metrica][1])+'</caption><thead><tr><th scope="col">Ano</th><th scope="col">Valor</th></tr></thead><tbody>'+rows.map(r=>'<tr'+(r.ano===ano?' style="background:#e9f0df;font-weight:700"':'')+'><th scope="row">'+r.ano+'</th><td>'+fmt(r.valor)+'</td></tr>').join('')+'</tbody></table>';
}
document.querySelectorAll('[data-secao]').forEach(b=>b.onclick=()=>mostrarSecao(b.dataset.secao));
$('serieEstado').onclick=()=>{selecionado=null;mapa.closePopup();renderSerie()};
$('opacidade').oninput=()=>{opacidade=Number($('opacidade').value)/100;$('opacidadeValor').textContent=Math.round(opacidade*100)+'%';camada.eachLayer(l=>l.setStyle({fillOpacity:opacidade}))};
$('enquadrar').onclick=()=>{mapa.fitBounds(camada.getBounds());mapa.closePopup()};
window.addEventListener('resize',()=>mapa.invalidateSize());

$('disponibilidade').textContent='PAM disponível neste projeto: '+Math.min(...P.info.anos)+'–'+Math.max(...P.info.anos)+'. Anos sem dados integrados ficam desativados.';$('consulta').textContent='Consulta à fonte: '+new Date(P.info.consulta_utc).toLocaleDateString('pt-BR')+'.';atualizar();setTimeout(()=>{mapa.invalidateSize();mapa.fitBounds(camada.getBounds())},100);
