const P=__PAYLOAD__, mapa=__MAPA__, camada=__CAMADA__;
const $=id=>document.getElementById(id), fmt=v=>v==null?'Sem dado':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:1});
const cores=['#edf8b1','#addd8e','#78c679','#31a354','#006837'];
let ano=String(Math.max(...P.info.anos)), metrica='214';
for(let a=2020;a<=2026;a++){const o=new Option(a+(P.info.anos.includes(a)?'':' · não publicado'),a);o.disabled=!P.info.anos.includes(a);$('ano').add(o)}$('ano').value=ano;
Object.entries(P.metricas).forEach(([k,v])=>$('metrica').add(new Option(v[0]+' ('+v[1]+')',k)));
Object.entries(P.nomes).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR')).forEach(([k,v])=>$('municipios').appendChild(new Option(v,v)));
const escalas={};for(const k of Object.keys(P.metricas)){const vs=Object.values(P.dados).flatMap(a=>Object.values(a).map(v=>v[k])).filter(v=>v!=null&&v>0).sort((a,b)=>a-b);escalas[k]=[.2,.4,.6,.8].map(q=>vs[Math.min(vs.length-1,Math.floor(vs.length*q))]||0)}
function cor(v){if(v==null)return '#bcbcbc';if(v===0)return '#fff';let i=escalas[metrica].findIndex(b=>v<=b);return cores[i<0?4:i]}
function escapar(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const layers={};camada.eachLayer(l=>{const c=l.feature.properties.codigo;layers[c]=l;l.on('click',()=>abrir(c))});
function abrir(c){const l=layers[c];if(!l)return;let rows=Object.keys(P.dados).sort().map(a=>`<tr><td>${a}</td><td>${fmt(P.dados[a]?.[c]?.[metrica])}</td></tr>`).join('');l.bindPopup(`<b>${escapar(P.nomes[c]||l.feature.properties.nome)}</b><p>${P.metricas[metrica][0]} · ${P.metricas[metrica][1]}</p><table class="serie"><tr><th>Ano</th><th>Valor</th></tr>${rows}</table><small>IBGE/PAM · código ${c}</small>`,{maxWidth:310}).openPopup()}
function atualizar(){ano=$('ano').value;metrica=$('metrica').value;mapa.closePopup();const d=P.dados[ano]||{},[titulo,unidade]=P.metricas[metrica];camada.eachLayer(l=>{let c=l.feature.properties.codigo,v=d[c]?.[metrica];l.setStyle({fillColor:cor(v),fillOpacity:.83,color:'#677b69',weight:.6});l.unbindTooltip();l.bindTooltip(escapar(P.nomes[c]||l.feature.properties.nome)+': '+fmt(v)+' '+unidade)});
$('numero').textContent=fmt(P.estado[ano]?.['35']?.[metrica]);$('unidade').textContent=titulo+' · '+unidade;$('cobertura').textContent=Object.values(d).filter(v=>v[metrica]!=null).length+' municípios com valor numérico / 645 municípios no mapa.';
const bs=escalas[metrica];$('legenda').innerHTML='<b>'+titulo+' · '+unidade+'</b>'+cores.map((c,i)=>`<div class="legenda"><i class="chip" style="background:${c}"></i>${i===0?'Maior que 0 até '+fmt(bs[0]):i===4?'Acima de '+fmt(bs[3]):'Acima de '+fmt(bs[i-1])+' até '+fmt(bs[i])}</div>`).join('')+'<div class="legenda"><i class="chip" style="background:white"></i>Zero <i class="chip" style="background:#bcbcbc"></i>Sem dado</div>';
$('ranking').replaceChildren();const ranking=Object.entries(d).filter(([c,v])=>v[metrica]!=null&&v[metrica]>0).sort((a,b)=>b[1][metrica]-a[1][metrica]).slice(0,10);$('rankingNota').textContent=ano+' · '+unidade;ranking.forEach(([c,v],i)=>{const li=document.createElement('li'),b=document.createElement('button');b.innerHTML=`<span>${i+1}. ${escapar(P.nomes[c])}</span><strong>${fmt(v[metrica])}</strong>`;b.onclick=()=>{mapa.fitBounds(layers[c].getBounds());abrir(c)};li.appendChild(b);$('ranking').appendChild(li)});}
$('ano').onchange=atualizar;$('metrica').onchange=atualizar;
function localizar(){let termo=$('busca').value.trim().toLocaleLowerCase('pt-BR');let c=Object.keys(P.nomes).find(c=>P.nomes[c].toLocaleLowerCase('pt-BR')===termo);$('buscaStatus').textContent=c?'':'Selecione um município da lista.';if(c&&layers[c]){mapa.fitBounds(layers[c].getBounds());abrir(c)}}$('localizar').onclick=localizar;$('busca').onkeydown=e=>{if(e.key==='Enter')localizar()};
$('baixar').onclick=e=>{e.preventDefault();const cell=v=>'"'+String(v??'').replace(/"/g,'""')+'"';let rows=[['ano','codigo_ibge','municipio',...Object.values(P.metricas).map(v=>v[0]+' ('+v[1]+')')],...Object.entries(P.dados[ano]).map(([c,v])=>[ano,c,P.nomes[c],...Object.keys(P.metricas).map(k=>v[k])])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(';')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='limao_sp_'+ano+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('disponibilidade').textContent='PAM disponível neste projeto: '+Math.min(...P.info.anos)+'–'+Math.max(...P.info.anos)+'. Anos não publicados ficam desativados.';$('consulta').textContent='Consulta à fonte: '+new Date(P.info.consulta_utc).toLocaleDateString('pt-BR')+'.';atualizar();setTimeout(()=>{mapa.invalidateSize();mapa.fitBounds(camada.getBounds())},100);
